### PR TITLE
Update documentation with alternative to create-react-app ejection

### PR DESCRIPTION
**Pull request by mvanlonden**

### CODE REVIEW

**Comment by alansouzati** [comment]
thanks

**Comment by alansouzati** [comment]
i still think it would be a good idea to create a repo with your configuration already enabled so that folks can easily fork/copy that.

**Comment by mvanlonden** [comment]
I'm not sure I fully understand. You mean a `create-react-app` project with `grommet-css` installed and imported into `index.js`?

**Comment by alansouzati** [comment]
Yes I think would be useful.

**Pull request merged**
